api_platform:
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    doctrine:
        enabled: true
    formats:
        json: ['application/json']
    title: project zara
    version: 1.0.0
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
        filters: ['api_platform.doctrine.orm.search_filter']
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]