monolog:
    channels: ["user", "api", "import", "export"]

    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/app.%kernel.environment%.log"
            level: debug
            max_files: 10
            channels: ['!user','!api', '!import','!export']

        user:
            type: rotating_file
            path: "%kernel.logs_dir%/user_log.%kernel.environment%.log"
            level: debug
            max_files: 30
            channels: ["user"]

        api:
            type: rotating_file
            path: "%kernel.logs_dir%/api_log.%kernel.environment%.log"
            level: debug
            max_files: 15
            channels: ["api"]

        import:
            type: rotating_file
            path: "%kernel.logs_dir%/import_log.%kernel.environment%.log"
            level: debug
            max_files: 10
            channels: ["import"]

        export:
            type: rotating_file
            path: "%kernel.logs_dir%/export_log.%kernel.environment%.log"
            level: debug
            max_files: 10
            channels: ["export"]
